const HomeActionTypes = {
    // FETCH
    FETCH_HOME_START: 'FETCH_HOME_START',
    FETCH_HOME_SUCCESS: 'FETCH_HOME_SUCCESS',
    FETCH_HOME_FAILURE: 'FETCH_HOME_FAILURE',

    // UPDATE
    UPDATE_HOME_START: 'UPDATE_HOME_START',
    UPDATE_HOME_SUCCESS: 'UPDATE_HOME_SUCCESS',
    UPDATE_HOME_FAILURE: 'UPDATE_HOME_FAILURE',

    // EDIT MODE
    CHANGE_EDIT_MODE: 'CHANGE_EDIT_MODE',

     // UPDATE HOME STATE LOCALLY
    UPDATE_HERO: 'UPDATE_HERO',
    UPDATE_FOOTER: 'UPDATE_HERO',
    UPDATE_INSPIRATION: 'UPDATE_INSPIRATION',
    UPDATE_CONTACT: 'UPDATE_CONTACT',
    UPDATE_VALUES: 'UPDATE_VALUES'

}

export default HomeActionTypes;